export const fontSize = {
  micro: "text-[9px]",
  caption: "text-[10px]",
  bodyXs: "text-[11px]",
  bodySm: "text-[12px]",
  pageTitle: "text-[18px]",
  kpiValue: "text-[24px]",
  operationalValue: "text-[28px]",
} as const;

export const fontWeight = {
  medium: "font-medium",
  semibold: "font-semibold",
  bold: "font-bold",
} as const;

export const letterSpacing = {
  normal: "tracking-normal",
  wide: "tracking-wide",
  wider: "tracking-wider",
  widest: "tracking-widest",
} as const;

export const textTransform = {
  none: "normal-case",
  uppercase: "uppercase",
  capitalize: "capitalize",
} as const;

export const typography = {
  pageEyebrow: `${fontSize.micro} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  pageTitle: `${fontSize.pageTitle} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.normal}`,
  sectionLabel: `${fontSize.micro} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  sectionDescription: `${fontSize.bodyXs}`,
  panelTitle: `${fontSize.caption} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  panelSubtitle: `${fontSize.micro} ${textTransform.uppercase} ${letterSpacing.wider}`,
  tableHeader: `${fontSize.micro} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  bodyMuted: `${fontSize.caption}`,
  bodyStrong: `${fontSize.bodyXs} ${fontWeight.semibold}`,
  metaStrong: `${fontSize.micro} ${fontWeight.semibold} ${textTransform.uppercase} ${letterSpacing.wider}`,
  emptyState: `${fontSize.bodyXs} ${fontWeight.semibold} ${textTransform.uppercase} ${letterSpacing.wide}`,
  rankingIndex: `font-mono ${fontSize.caption} ${fontWeight.bold} ${letterSpacing.normal}`,
  kpiValue: `${fontSize.kpiValue} ${fontWeight.bold} ${letterSpacing.normal}`,
  operationalValue: `${fontSize.operationalValue} ${fontWeight.bold} ${letterSpacing.normal}`,
  operationalCodeValue: `font-mono ${fontSize.operationalValue} ${fontWeight.bold} ${letterSpacing.normal}`,
  pageCodeTitle: `font-mono ${fontSize.pageTitle} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.normal}`,
  code: `font-mono ${fontSize.bodyXs} ${fontWeight.bold} ${letterSpacing.normal}`,
  codeMuted: `font-mono ${fontSize.caption} ${letterSpacing.normal}`,
  logCode: `font-mono ${fontSize.caption} ${letterSpacing.normal} leading-4`,
  badge: `font-mono ${fontSize.micro} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  badgeLg: `font-mono ${fontSize.caption} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  badgeXl: `font-mono text-[13px] ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  action: `${fontSize.caption} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
  linkAction: `${fontSize.micro} ${fontWeight.bold} ${textTransform.uppercase} ${letterSpacing.widest}`,
} as const;

export const surface = {
  pageStack: "space-y-5",
  pageStackContained: "space-y-5 mx-auto",
  pageHeader: "border-b-2 border-border pb-4",
  pageHeaderResponsive:
    "flex flex-col gap-4 border-b-2 border-border pb-4 sm:flex-row sm:items-start sm:justify-between",
  pageHeaderResponsiveCompact:
    "flex flex-col gap-3 border-b-2 border-border pb-4 sm:flex-row sm:items-start sm:justify-between",
  panel: "overflow-hidden rounded-lg border border-border bg-card shadow-sm",
  card: "rounded-lg border border-border bg-card shadow-sm",
  liftCard: "andcheck-lift rounded-lg border border-border bg-card shadow-sm",
  kpiCard: "andcheck-lift rounded-lg border border-l-4 bg-card p-3 shadow-sm sm:p-4",
  kpiCardHeader: "mb-3 flex items-start justify-between gap-3",
  subtleBox: "rounded-lg border border-border bg-muted/20",
  dashedBox: "border border-dashed border-border bg-muted/20",
  dashedActionBox:
    "border border-dashed border-border bg-muted/20 transition-colors hover:bg-muted/40",
  dashedIconButton: "border border-dashed border-border bg-transparent hover:bg-muted/20",
  dashedThumbButton: "border border-dashed border-border bg-muted/20 hover:bg-muted/20",
  mutedFill: "bg-muted/20",
  mutedFillStrong: "bg-muted/30",
  neutralTile: "border-border bg-card",
  mutedTile: "border-border bg-muted/40",
  mutedInset: "rounded-md border border-border bg-muted/30",
  mutedInsetLight: "rounded-md border border-border bg-muted/40",
  mutedInsetStrong: "rounded-md border border-border bg-muted/50",
  readonlyInset: "border border-border bg-muted/40",
  softInset: "rounded-md border border-border/70 bg-muted/15",
  outlinedBox: "rounded-md border border-border p-3",
  gridCell: "min-w-0 bg-card p-3",
  gridCellLg: "min-w-0 bg-card p-4",
  expandedRow: "border-t border-border bg-muted/15",
  outlinedChip: "rounded-md border border-border/70",
  badgeChip: "inline-flex items-center gap-1 rounded-md border px-2 py-0.5",
  dialog: "rounded-lg border border-border bg-card shadow-lg",
  popover:
    "rounded-md border border-border bg-card shadow-lg",
  floatingPanel: "border-b border-border bg-background shadow-lg",
  subtleDividerBar: "border-b border-border/70",
  desktopTopbar: "border-b border-border bg-card",
  operationalHero: "border-l-4 border-l-sidebar-primary bg-sidebar shadow-sm",
  accountHeader: "border-b bg-muted/25 p-4",
  tableFrame: "overflow-x-auto rounded-lg border border-border",
  flatTableFrame: "overflow-x-auto border border-border",
  mediaFrame: "overflow-hidden rounded-md border border-border",
  documentFrame: "border border-border",
  fileIconBox: "border border-border bg-background",
  warningAlert: "border border-amber-300 bg-amber-50 text-amber-950",
  warningAlertMuted: "border border-amber-200 bg-amber-50 text-amber-800",
  dangerAlert: "border border-destructive/30 bg-destructive/5 text-destructive",
  dangerAlertStrong:
    "border border-destructive/30 bg-destructive/10 text-destructive",
  infoAlert: "border border-blue-200 bg-blue-50 text-blue-900",
  successAlert: "border border-emerald-200 bg-emerald-50 text-emerald-800",
  darkHeaderButton:
    "text-primary-foreground/70 hover:bg-white/10 hover:text-primary-foreground",
  panelHeader: "bg-sidebar px-4 py-3 text-sidebar-foreground",
  modalHeaderDark:
    "border-b border-sidebar-border bg-sidebar px-4 py-3 text-sidebar-foreground",
  modalHeaderDarkWide:
    "border-b border-sidebar-border bg-sidebar px-4 py-4 text-sidebar-foreground sm:px-5",
  panelHeaderMuted: "border-b-2 border-border bg-muted/40 px-4 py-2.5",
  panelHeaderWide: "border-b-2 border-border bg-muted/40 px-5 py-3",
  panelHeaderSubtle: "border-b-2 border-border bg-muted/30 px-4 py-3",
  panelHeaderAccent: "border-b border-border bg-primary/5 px-4 py-2",
  panelHeaderBare: "border-b border-border bg-card",
  panelHeaderCompact: "border-b border-border px-4 py-2",
  panelHeaderSticky: "sticky top-0 z-10 border-b border-border bg-popover p-2",
  popoverHeader: "border-b border-border px-2.5 py-1.5",
  panelFooter: "border-t border-border bg-muted/30 px-4 py-2",
  panelFooterCompact: "border-t border-border px-2.5 py-1.5",
  popoverFooter: "border-t border-border px-2.5 py-1.5",
  noteFooter: "border-t border-border px-3 py-2",
  linkFooter: "border-t border-border px-4 py-3",
  linkFooterInteractive: "border-t border-border px-4 py-3 hover:bg-muted/40",
  actionFooter: "border-t border-border bg-muted/20 px-4 py-3",
  actionFooterPlain: "border-t border-border pt-2",
  rowDivider: "border-b border-border last:border-0",
  rowDividerSoft: "border-b border-border/50",
  tableRowDivider: "border-t border-border",
  listDivider: "divide-y divide-border",
  detailRow: "border-b border-border px-4 py-2.5 last:border-0",
  rowStripedEven: "bg-card",
  rowStripedOdd: "bg-muted/20",
  rowInteractive: "transition-colors hover:bg-muted/30",
  rowPrimaryInteractive: "transition-colors hover:bg-primary/5",
  sectionDivider: "border-b border-border pb-2",
  sectionBlock: "border-b border-border p-4 sm:p-5",
  topDivider: "border-t border-border pt-3",
  panelHeaderIcon: "w-3.5 h-3.5 text-sidebar-foreground/70",
  panelHeaderTitle: `${typography.panelTitle} text-sidebar-foreground`,
  panelHeaderSubtitle: `${typography.panelSubtitle} text-sidebar-foreground/45`,
  tableHeader: `border-b border-border bg-sidebar px-4 py-3 text-sidebar-foreground ${typography.tableHeader}`,
  tableHeaderCellMuted: "text-primary-foreground/60",
  onDarkMutedText: "text-primary-foreground/60",
  onDarkSubtleText: "text-primary-foreground/40",
  onDarkIcon: "text-primary-foreground/80",
  tableFooter: `border-t border-border bg-muted/30 px-4 py-2 text-muted-foreground/50`,
  panelEmptyState: "border-0 border-b border-dashed",
  panelEmptyStatePadded: "border-0 border-b border-dashed py-8",
} as const;

export const control = {
  inputSm: `h-8 rounded-md border-border ${typography.sectionDescription}`,
  inputSmWithIcon: `h-8 rounded-md border-border pl-9 ${typography.sectionDescription}`,
  inputMd: `h-9 rounded-md ${typography.bodyStrong}`,
  inputMdMuted: `h-9 rounded-md ${typography.sectionDescription}`,
  selectSm: `h-8 rounded-md ${typography.sectionDescription}`,
  selectMd: `h-9 rounded-md ${typography.bodyStrong}`,
  buttonSm: `h-8 rounded-md ${typography.action}`,
  outlineButtonSm: `h-8 gap-1.5 rounded-md border border-border/70 px-3 ${typography.action}`,
  buttonMd: `h-9 rounded-md ${typography.action}`,
  legendButtonActive: "border-accent bg-accent/10 text-foreground",
  legendButtonInactive: "border-border text-muted-foreground hover:bg-muted/60",
  nativeSelectSm:
    `h-8 w-full rounded-md border border-input bg-transparent px-2.5 text-foreground outline-none transition-[background-color,border-color,box-shadow,color] hover:border-muted-foreground/45 focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 ${typography.sectionDescription}`,
  contextSelect:
    "h-9 border-0 bg-transparent px-2 shadow-none hover:bg-muted/60 focus-visible:ring-1",
} as const;
