allowBuilds:
  '@prisma/engines': true
  core-js: false
  msw: false
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  '@hono/node-server': 1.19.13
  '@opentelemetry/core': 2.8.0
  dompurify: 3.4.11
  postcss: 8.5.10
  undici: 6.27.0
