ALTER TYPE "AuditEntityType" ADD VALUE 'WORKSPACE';
ALTER TYPE "AuditAction" ADD VALUE 'WORKSPACE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKSPACE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKSPACE_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'WORKSPACE_DEACTIVATED';

ALTER TABLE "workspaces" ADD COLUMN "description" TEXT;
