ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'NOTIFICATION';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_READ';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_ARCHIVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'NOTIFICATION_EMAIL_RESENT';
